export const listNameOptions = [
  { label: 'Blind 75', value: 'Blind 75' },
  { label: 'NeetCode 150', value: 'Neetcode 150' },
  { label: 'NeetCode All', value: 'Neetcode All' }
];

export const difficultyListOptions = [
  { label: 'Easy', value: 'Easy' },
  { label: 'Medium', value: 'Medium' },
  { label: 'Hard', value: 'Hard' }
];

export const categoryListOptions = [
  { label: 'Array & Hashing', value: 'Array & Hashing' },
  { label: 'Hash Table', value: 'Hash Table' },
  { label: 'Linked List', value: 'Linked List' },
  { label: 'Stack', value: 'Stack' },
  { label: 'Heap & Priority Queue', value: 'Heap & Priority Queue' },
  { label: 'Binary Search', value: 'Binary Search' },
  { label: 'Binary Tree', value: 'Binary Tree' },
  { label: 'Merge Sort', value: 'Merge Sort' },
  { label: 'Quick Sort', value: 'Quick Sort' },
  { label: 'Recursion', value: 'Recursion' },
  { label: 'Depth-First Search', value: 'Depth-First Search' },
  { label: 'Breath-First Search', value: 'Breath-First Search' },
  { label: 'Backtracking', value: 'Backtracking' },
  { label: 'Shortest Path', value: 'Shortest Path' },
  { label: 'Greedy', value: 'Greedy' },
  { label: 'Intervals', value: 'Intervals' },
  { label: 'Tree', value: 'Tree' },
  { label: 'Graph', value: 'Graph' },
  { label: 'Trie', value: 'Trie' },
  { label: 'Two Pointers', value: 'Two Pointers' },
  { label: 'Sliding window', value: 'Sliding window' },
  { label: 'Prefix Sum', value: 'Prefix Sum' },
  { label: 'Advanced Graph', value: 'Advanced Graph' },
  { label: '1D Dynamic Programming', value: '1D Dynamic Programming' },
  { label: '2D Dynamic Programming', value: '2D Dynamic Programming' },
  { label: 'Math & Geometry', value: 'Math & Geometry' },
  { label: 'Bit Manipulation', value: 'Bit Manipulation' }
];

export const tagListOptions = [
  { label: 'Array', value: 'Array' },
  { label: 'Hash Table', value: 'Hash Table' },
  { label: 'Hashing', value: 'Hashing' },
  { label: 'Linked List', value: 'Linked List' },
  { label: 'Stack', value: 'Stack' },
  { label: 'Heap & Priority Queue', value: 'Heap & Priority Queue' },
  { label: 'Binary Search', value: 'Binary Search' },
  { label: 'Merge Sort', value: 'Merge Sort' },
  { label: 'Quick Sort', value: 'Quick Sort' },
  { label: 'Recursion', value: 'Recursion' },
  { label: 'Depth-First Search', value: 'Depth-First Search' },
  { label: 'Breath-First Search', value: 'Breath-First Search' },
  { label: 'Backtracking', value: 'Backtracking' },
  { label: 'Dijkstra', value: 'Dijkstra' },
  { label: 'Prim', value: 'Prim' },
  { label: 'Shortest Path', value: 'Shortest Path' },
  { label: 'Greedy', value: 'Greedy' },
  { label: 'Intervals', value: 'Intervals' },
  { label: 'Tree', value: 'Tree' },
  { label: 'Graph', value: 'Graph' },
  { label: 'Trie', value: 'Trie' },
  { label: 'Two Pointers', value: 'Two Pointers' },
  { label: 'Sliding window', value: 'Sliding window' },
  { label: 'Prefix Sum', value: 'Prefix Sum' },
  { label: 'Memoization', value: 'Memoization' },
  { label: 'Union Find', value: 'Union Find' },
  { label: 'Monotonic Stack', value: 'Monotonic Stack' },
  { label: 'Advanced Graph', value: 'Advanced Graph' },
  { label: '1D Dynamic Programming', value: '1D Dynamic Programming' },
  { label: '2D Dynamic Programming', value: '2D Dynamic Programming' },
  { label: 'Math & Geometry', value: 'Math & Geometry' },
  { label: 'Bit Manipulation', value: 'Bit Manipulation' },
  { label: 'Topological Sort', value: 'Topological Sort' },
  { label: 'Segment Tree', value: 'Segment Tree' },
  { label: 'Palindromes', value: 'Palindromes' },
  { label: 'Combination', value: 'Combination' },
  { label: 'Permutations', value: 'Permutations' }
];

export const companyListOption = [
  { label: 'Adobe', value: 'Adobe' },
  { label: 'AirBnB', value: 'AirBnB' },
  { label: 'Amazon', value: 'Amazon' },
  { label: 'Apple', value: 'Apple' },
  { label: 'Bloomberg', value: 'Bloomberg' },
  { label: 'Coinbase', value: 'Coinbase' },
  { label: 'Cisco', value: 'Cisco' },
  { label: 'Coinbase', value: 'Coinbase' },
  { label: 'eBay', value: 'eBay' },
  { label: 'DoorDash', value: 'DoorDash' },
  { label: 'Facebook (Meta)', value: 'Facebook (Meta)' },
  { label: 'Google', value: 'Google' },
  { label: 'Intel', value: 'Intel' },
  { label: 'LinkedIn', value: 'LinkedIn' },
  { label: 'Lyft', value: 'Lyft' },
  { label: 'Intel', value: 'Intel' },
  { label: 'Netflix', value: 'Netflix' },
  { label: 'Microsoft', value: 'Microsoft' },
  { label: 'Oracle', value: 'Oracle' },
  { label: 'Microsoft', value: 'Microsoft' },
  { label: 'Paypal', value: 'Paypal' },
  { label: 'Twitter', value: 'Twitter' },
  { label: 'Twitch', value: 'Twitch' },
  { label: 'Saleforces', value: 'Saleforces' },
  { label: 'SpotifyUber', value: 'SpotifyUber' },
  { label: 'TikTok', value: 'TikTok' },
  { label: 'Uber', value: 'Uber' },
  { label: 'Walmart', value: 'Walmart' },
  { label: 'Yahoo', value: 'Yahoo' }
];

export const categorySelection = [
  'Array & Hashing',
  'Hash Table',
  'Linked List',
  'Stack',
  'Heap & Priority Queue',
  'Binary Search',
  'Merge Sort',
  'Quick Sort',
  'Recursion',
  'Depth-First Search',
  'Breath-First Search',
  'Backtracking',
  'Shortest Path',
  'Greedy',
  'Intervals',
  'Tree',
  'Graph',
  'Trie',
  'Two Pointers',
  'Sliding window',
  'Prefix Sum',
  'Advanced Graph',
  '1D Dynamic Programming',
  '2D Dynamic Programming',
  'Math & Geometry',
  'Bit Manipulation'
];

export const tagSelection = [
  'Array',
  'Hash Table',
  'Hashing',
  'Linked List',
  'Stack',
  'Heap & Priority Queue',
  'Binary Search',
  'Binary Tree',
  'Merge Sort',
  'Quick Sort',
  'Recursion',
  'Depth-First Search',
  'Breath-First Search',
  'Backtracking',
  'Dijkstra',
  'Prim',
  'Shortest Path',
  'Greedy',
  'Intervals',
  'Tree',
  'Graph',
  'Trie',
  'Two Pointers',
  'Sliding window',
  'Prefix Sum',
  'Memoization',
  'Union Find',
  'Monotonic Stack',
  'Advanced Graph',
  '1D Dynamic Programming',
  '2D Dynamic Programming',
  'Math & Geometry',
  'Bit Manipulation',
  'Topological Sort',
  'Segment Tree',
  'Palindromes',
  'Combination',
  'Permutations'
].sort();

export const companies = [
  'Adobe',
  'AirBnB',
  'Amazon',
  'Apple',
  'Bloomberg',
  'Coinbase',
  'Cisco',
  'eBay',
  'DoorDash',
  'Facebook (Meta)',
  'Google',
  'Intel',
  'LinkedIn',
  'Lyft',
  'Netflix',
  'Microsoft',
  'Oracle',
  'Paypal',
  'Twitter',
  'Twitch',
  'Saleforces',
  'Spotify',
  'TikTok',
  'Uber',
  'Walmart',
  'Yahoo'
];
